"""Analyst-style GitHub metrics: live repo stats -> self-contained metrics.html."""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path


def _token() -> str:
    hosts = Path.home() / ".config" / "gh" / "hosts.yml"
    if not hosts.exists():
        return ""
    m = re.search(r"oauth_token:\s*(\S+)", hosts.read_text())
    return m.group(1) if m else ""


def _api(url: str, token: str) -> dict | list:
    req = urllib.request.Request(
        url, headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def fetch(owner: str, repo: str) -> dict:
    token = _token()
    repo_data = _api(f"https://api.github.com/repos/{owner}/{repo}", token)
    contribs = _api(f"https://api.github.com/repos/{owner}/{repo}/stats/contributors", token)
    langs = _api(f"https://api.github.com/repos/{owner}/{repo}/languages", token)
    total_commits = sum(c.get("total", 0) for c in contribs) if isinstance(contribs, list) else 0
    return {
        "name": repo_data.get("full_name"),
        "visibility": repo_data.get("visibility"),
        "stars": repo_data.get("stargazers_count", 0),
        "forks": repo_data.get("forks_count", 0),
        "open_issues": repo_data.get("open_issues_count", 0),
        "pushed_at": repo_data.get("pushed_at", ""),
        "default_branch": repo_data.get("default_branch", "main"),
        "contributors": len(contribs) if isinstance(contribs, list) else 0,
        "commits": total_commits,
        "languages": langs,
    }


def render(metrics: dict) -> str:
    langs = sorted(metrics["languages"].items(), key=lambda kv: kv[1], reverse=True)
    total = sum(v for _, v in langs) or 1
    lang_bars = "\n".join(
        f'<div style="display:flex;justify-content:space-between;font-size:13px;padding:4px 0">'
        f'<span>{k}</span><span>{100 * v // total}%</span></div>'
        f'<div style="height:6px;background:rgba(255,255,255,.08);border-radius:4px;margin-bottom:6px">'
        f'<div style="height:6px;width:{100 * v // total}%;border-radius:4px;background:var(--grad)"></div></div>'
        for k, v in langs[:6]
    )
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Repo Metrics — {metrics['name']}</title><style>
:root{{--bg:#0b0f1a;--panel:#121a2e;--ink:#e8edf7;--mut:#8aa0c6;
--grad:linear-gradient(135deg,#6d83ff,#9b5cff 45%,#ff5ca8);--line:rgba(255,255,255,.08)}}
*{{box-sizing:border-box}}body{{margin:0;font:15px/1.5 system-ui,sans-serif;color:var(--ink);
background:radial-gradient(800px 400px at 10% -10%,rgba(109,131,255,.2),transparent 60%),var(--bg);min-height:100%}}
.wrap{{max-width:900px;margin:0 auto;padding:40px 20px}}h1{{font-size:22px;margin:0 0 4px}}
.sub{{color:var(--mut);font-size:13px}}.stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px;margin:24px 0}}
.stat{{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:16px}}
.stat .k{{font-size:24px;font-weight:700;background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent}}
.stat .l{{color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.06em;margin-top:4px}}
.panel{{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:18px;margin-top:16px}}
footer{{color:var(--mut);font-size:12px;margin-top:36px;text-align:center}}
a{{color:#9cb4ff}}</style></head><body><div class="wrap">
<h1>{metrics['name']}</h1><div class="sub">Live metrics · {metrics['visibility']} · default branch {metrics['default_branch']}</div>
<div class="stats">
<div class="stat"><div class="k">{metrics['stars']}</div><div class="l">Stars</div></div>
<div class="stat"><div class="k">{metrics['forks']}</div><div class="l">Forks</div></div>
<div class="stat"><div class="k">{metrics['open_issues']}</div><div class="l">Open issues</div></div>
<div class="stat"><div class="k">{metrics['contributors']}</div><div class="l">Contributors</div></div>
<div class="stat"><div class="k">{metrics['commits']}</div><div class="l">Commits</div></div>
</div>
<div class="panel"><b>Languages</b>{lang_bars}</div>
<div class="panel"><b>Last push</b><br/><span style="color:var(--mut)">{metrics['pushed_at']}</span></div>
<footer>Auto-generated by the hub's GitHub metrics script · <a href="dashboard.html">← back to hub</a></footer>
</div></body></html>"""


def main() -> int:
    import sys

    parts = (sys.argv[1] if len(sys.argv) > 1 else "adjjvmorii26-png/agent-workforce").split("/")
    metrics = fetch(parts[0], parts[1])
    out = Path("metrics.html")
    out.write_text(render(metrics), encoding="utf-8")
    print(f"metrics -> {out.resolve()} ({len(metrics['languages'])} languages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
